# Generated by Django 4.1.1 on 2022-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordspatients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='female',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='male',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
