# Generated by Django 4.1.1 on 2022-09-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordspatients', '0002_remove_patient_female_remove_patient_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='female',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='male',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
